name: 'Monday Code Deploy'
description: 'Deploy app to Monday code'
inputs:
  token:
    description: 'Monday developer token'
    required: true
  appId:
    description: 'The ID of your monday app'
    required: false
  region:
    description: 'The region to deploy the app to (us, eu, au)'
    required: false
  versionId:
    description: 'The app version ID to deploy to'
    required: false
  force:
    description: 'Force push to the latest version (draft or live)'
    required: false
  client:
    description: 'Push client side code to cdn'
    required: false
  dirPath:
    description: 'Path to the directory to upload'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.token }}
  - ${{ inputs.appId }}
  - ${{ inputs.region }}
  - ${{ inputs.versionId }}
  - ${{ inputs.force }}
  - ${{ inputs.client }}
  - ${{ inputs.dirPath }}
